### ISSUE TITLE
IAT 1.90 - no blue edit button appears/hot key doesn't work - Firefox 36.0

### ISSUE THREAD

**Issue by NewMexicoKid** [docwhat/itsalltext#66] opened 2015-02-25 16:17 UTC
## Environment
* OS: Windows 7 64 bit
* Firefox: 36.0 (also seen in Firefox 35.0.1)
* IAT: 1.90

## Symptoms
* No blue Edit button pops up when hovering in the selected (upper right) corner of the text area box
* Assigned hot key (F10) doesn't invoke IAT
* The right click context menu can invoke IAT (gvim 7.2)

**Comment by docwhat** [comment] 2015-02-25 23:14
Thanks for the report... something definitely seems wrong on Windows.  This is a duplicate of issue #65, so I'm closing it... but feel free to follow on #65.

**Closed by docwhat** 2015-02-25 23:14 UTC
