### ISSUE TITLE
IAT automatically overwrites the textarea in the browser with the value it has stored previously on disk

### ISSUE THREAD

**Issue by lucaa** [docwhat/itsalltext#44] opened 2013-05-29 09:32 UTC
I think this is thought as a feature, but for me is a bug, my usecase is described below.

I use IAT to edit wiki pages, which other people can collaborate to as well. To reproduce the issue:
* open up a wiki page in edit mode, edit it with IAT with an editor of your choice
* do some modifications, save the wiki page, exit the edit mode (make the textarea dissappear). Also close the external editor opened by IAT. 

At this point, you can see on the disk in the IAT folder that the file that was edited is still there
* open the wiki page in edit mode in a different browser, make some modifications, save.
* go back to firefox, edit again the page (so that the textarea appears again).

At this point, the content of the textarea which was previously edited with the external editor with IAT will be filled in automatically with the content found on the disk in the IAT folder. This will overwrite the changes that were made in the other browser, and there is no way to be able to edit the page with these changes, except going in the IAT folder and removing all 'cached' files.

NOTE that this problem does not reproduce with IAT 1.6.4, meaning that even if the file stays on the disk and all, the textarea is not automatically filled in with the content on the disk, and when choosing to open the external editor, the file on the disk is overwritten with the new value of the textarea.

I am on kubuntu 13.04, Firefox 21.0, It's all text 1.8.1.  I tried with both kate and gedit editors, I get the same behaviour.

Besides that, great job, lovely extension.

**Comment by docwhat** [comment] 2015-02-22 20:30
Okay, I'm back...

Lessee: @scotto, that change shouldn't have effected it at all.  The key bit is the the `clobber` flag passed to `cacheobj.edit()`.

I can't reproduce this using my test page: https://docwhat.org/files/iat/revisit.html  -- Are you able to?

**Comment by xOneca** [comment] 2015-02-23 00:24
I was stuck in 1.6.4 because of this, but I have just tried master and seems fixed. I'll test a week more or so to confirm...

Where's the fix for this? I cannot find a concrete commit.

**Comment by docwhat** [comment] 2015-02-23 00:33
I have no idea. Isn't software wonderful? :grinning:

**Comment by docwhat** [comment] 2015-02-23 15:41
V1.9.0 has been released.

**Comment by xOneca** [comment] 2015-02-26 11:23
I have bad news: IAT 1.9.0 is overwriting the text in Trac. So, problem not solved, that's why I couldn't find the fix, I think... ;)

**Comment by docwhat** [comment] 2015-02-26 13:27
Can you reproduce the bug on https://docwhat.org/files/iat/revisit.html

If not can you give URLs to reproduce it and steps?

**Comment by xOneca** [comment] 2015-02-26 13:36
Yes, with latest 1.9.1 from AMO.

**Comment by docwhat** [comment] 2015-02-26 13:39
OS?

**Comment by xOneca** [comment] 2015-02-26 13:40
openSUSE 13.1 (x86_64)

**Comment by xOneca** [comment] 2015-02-26 13:40
I am currently bisecting source, and found commit 10461c6e1aa5bafa79d37ce3d0b9dc1a74953a00 is the first failing.

**Comment by xOneca** [comment] 2015-02-26 13:50
(All comming references to `cacheobj.js`) The first call to `setExtension()` in `initFromExistingFile()` does not detect file as existing, and `this.timestamp` and `this.size` remain as `0`. Then `hasChanged()` detects file as modified, and `update()` loads content from file.

I'm investigating why does the `file.exists()` in `setExtension()` return false.

**Comment by xOneca** [comment] 2015-02-26 14:29
Yeah!! Bug found!!

Function `setExtension()` was instantiating the file object **before** setting the found extension so it was using the default extension for the file name. I'm preparing a pull request right now.

**Comment by ilpssun** [comment] 2015-09-22 07:50
I'm using IAT! 1.9.1.1-signed and can still reproduce the bug on https://docwhat.org/files/iat/revisit.html:
* Edit as custom extension, e.g., `.md`.
* Edit and save file in text editor → input field updated
* Close webpage, edit file again in text editor
* Reopen webpage → input field updated to new value

So it seems not to be fixed for 1.9.1.1 – is that correct?  When will the fix be released?

BTW: It works well when I use the default `.txt` extension.

**Comment by scotto** [comment] 2015-09-22 13:53
Same issue here.  If I follow the procedure on the [test page](https://docwhat.org/files/iat/revisit.html) (ie, click the edit button to edit as text), it works fine.  BUT, if I right-click on the text area, choose "It's All Text!" from the context menu, the choose "Edit as .html", the old always-overwrite problem shows up as @iplssun outlines above.

**Comment by xOneca** [comment] 2015-09-22 23:37
The fix is in the repository, but it's still not released. This bug was fixed hours **after** 1.9.1 was released.

**Comment by astsmtl** [comment] 2015-09-23 13:29
It's a critical bug, so it's better to release new version.

**Comment by docwhat** [comment] 2015-09-23 17:02
1.9.2 has been uploaded for approval. It should be out shortly.

**Comment by docwhat** [comment] 2015-09-23 17:03
@xOneca Sorry I forgot about this.  Thanks for pointing it out.

**Closed by docwhat** 2015-09-23 17:02 UTC

**Comment by scotto** [comment] 2015-09-25 14:12
Oooh, that's so much better -- thanks for pushing that out the door 1.9.2 out the door!  Very nice.

**Comment by xOneca** [comment] 2015-09-25 14:44
Don't worry for me @docwhat, I had the fixed 1.9.1 :stuck_out_tongue_closed_eyes:

Now I can enable again automatic updates! :smile:
